FROM node:24.5.0-slim AS builder

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/openperplexity

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY tsconfig.json next.config.mjs next-env.d.ts postcss.config.js drizzle.config.ts tailwind.config.ts ./
COPY src ./src
COPY public ./public
COPY drizzle ./drizzle

RUN mkdir -p /home/openperplexity/data
RUN yarn build

FROM node:24.5.0-slim

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/openperplexity

COPY --from=builder /home/openperplexity/public ./public
COPY --from=builder /home/openperplexity/.next/static ./public/_next/static
COPY --from=builder /home/openperplexity/.next/standalone ./
COPY --from=builder /home/openperplexity/data ./data
COPY drizzle ./drizzle

RUN mkdir /home/openperplexity/uploads

EXPOSE 3000

CMD ["node", "server.js"]
